nqostatsweb/src/nqostatsweb/Models/Players.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace nqostatsweb.Models
{
    public class Players
    {
        public int Id { get; set; }
        [StringLength(20)]
        public string IpAddress { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        public List<MatchPlayerStats> PlayerStats { get; set; }
    }
}

nqostatsweb/src/nqostatsweb/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using nqostatsweb.Data;
using nqostatsweb.Models;

namespace nqostatsweb.Controllers
{
    public class PlayersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlayersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            var temp = _context.MatchPlayerStats.ToListAsync();
            return View(await _context.Players.ToListAsync());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.SingleOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            //var temp = await _context.MatchPlayerStats.ToListAsync();
            var temp = await _context.MatchPlayerStats.Where(p => p.PlayerId == player.Id).ToListAsync();
            return View(temp);
        }

        // GET: Players/Create
        public async Task<IActionResult> Highlights()
        {
            List<MatchPlayerStats> listItems = new List<MatchPlayerStats>();

            return View(listItems.ToList());
        }

        public IActionResult Badstats()
        {
            return View();
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Players player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.SingleOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Players player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.SingleOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Players.SingleOrDefaultAsync(m => m.Id == id);
            _context.Players.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PlayerExists(int id)
        {
            return _context.Players.Any(e => e.Id == id);
        }
    }
}

nqostatsweb/src/nqostatsweb/ViewComponents/TopFragsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using nqostatsweb.Data;
using nqostatsweb.Models.PlayersViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nqostatsweb.ViewComponents
{
    public class TopFragsViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public TopFragsViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await GetItemsAsync();
            return View(items);
        }
        private Task<List<TopFragsViewModel>> GetItemsAsync()
        {
            var startDate = new DateTime(2017, 03, 21);
            var endDate = new DateTime(2017, 06, 21);

            var items = from T1 in _context.Players
                        join T2 in _context.MatchPlayerStats on T1.Id equals T2.PlayerId
                        join T3 in _context.Match on T2.MatchId equals T3.Id
                        where T3.Date >= startDate && T3.Date < endDate
                        group new
                        {
                            T1,
                            T2,
                        }
                        by new
                        {
                            T1.Id,
                            T1.Name
                        } into g
                        select new TopFragsViewModel
                        {
                            Name = g.Key.Name,
                            PlayerTotalNumberOfFrags = g.Sum(T2 => T2.T2.NumOfFrags)
                        };

            items = items.OrderByDescending(x => x.PlayerTotalNumberOfFrags);
            items.ToListAsync();
            items = items.Take(5);

            return items.ToListAsync();
        }
    }
}

nqostatsweb/src/nqostatsweb/ViewComponents/TopKDRViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using nqostatsweb.Data;
using nqostatsweb.Models.PlayersViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nqostatsweb.ViewComponents
{
    public class TopKDRViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public TopKDRViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await GetItemsAsync();
            return View(items);
        }
        private Task<List<TopKDRViewModel>> GetItemsAsync()
        {
            // call top 5 win percent
            var items = _context.Set<TopKDRViewModel>().FromSql("call Top5KDR('2017-03-21','2017-06-21')");
            items.ToListAsync();
            items = items.Take(5);
            return items.ToListAsync();
        }
    }
}

nqostatsweb/src/nqostatsweb/ViewComponents/TopQuadsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using nqostatsweb.Data;
using nqostatsweb.Models;
using nqostatsweb.Models.PlayersViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nqostatsweb.ViewComponents
{
    public class TopQuadsViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public TopQuadsViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await GetItemsAsync();
            return View(items);
        }
        private Task<List<TopQuadsViewModel>> GetItemsAsync()
        {
            var startDate = new DateTime(2017, 03, 21);
            var endDate = new DateTime(2017, 06, 21);

            var items = from T1 in _context.Players
                        join T2 in _context.MatchPlayerStats on T1.Id equals T2.PlayerId
                        join T3 in _context.Match on T2.MatchId equals T3.Id
                        where T3.Date >= startDate && T3.Date < endDate
                        group new
                        {
                            T1,
                            T2
                        }
                        by new
                        {
                            T1.Id,
                            T1.Name
                        }into g
                        select new TopQuadsViewModel
                        {
                            PlayerId = g.Key.Id,
                            Name = g.Key.Name,
                            PlayerTotalNumberOfQuads = g.Sum(T2 => T2.T2.NumberOfQuads)
                        };


            items = items.OrderByDescending(x => x.PlayerTotalNumberOfQuads);
            items.ToListAsync();
            items = items.Take(5);

            return items.ToListAsync();
        }
    }
}   

nqostatsweb/src/nqostatsweb/ViewComponents/TopWinsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using nqostatsweb.Data;
using nqostatsweb.Models.PlayersViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nqostatsweb.ViewComponents
{
    public class TopWinsViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public TopWinsViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await GetItemsAsync();
            return View(items);
        }
        private Task<List<TopWinsViewModel>> GetItemsAsync()
        {
            var startDate = new DateTime(2017, 03, 21);
            var endDate = new DateTime(2017, 06, 21);

            var items = from T1 in _context.Players
                        join T2 in _context.MatchPlayerStats on T1.Id equals T2.PlayerId
                        join T3 in _context.MatchTeamStats on T2.MatchId equals T3.MatchId
                        join T4 in _context.Match on T2.MatchId equals T4.Id
                        where T2.TeamColor == T3.TeamColor
                        && T3.TeamVerdict == "win"
                        && T4.Date >= startDate 
                        && T4.Date < endDate
                        group new
                        {
                            T1,
                            T2,
                        }
                        by new
                        {
                            T1.Id,
                            T1.Name
                        } into g
                        select new TopWinsViewModel
                        {
                            Name = g.Key.Name,
                            PlayerTotalNumberOfWins = g.Count()
                        };

            items = items.OrderByDescending(x => x.PlayerTotalNumberOfWins);
            items = items.Where(x => !x.Name.ToLower().Equals("unknownplayer"));
            items.ToListAsync();
            items = items.Take(5);
            

            return items.ToListAsync();
        }
    }
}

nqostatsweb/src/nqostatsweb/Views/Players/Badstats.cshtml
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="row-fluid">
    <div class="span4">
        <div class="well">
            <h4>Highest Avg. Team Kills</h4>
            <div>
                @await Component.InvokeAsync("TopTeamKills")
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="well">
            <h4>Highest Avg. Dropped Paks</h4>
            <div>
                @*@await Component.InvokeAsync("TopWinPercent")*@
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="well">
            <h4>Losing Streak</h4>
            <div>
                @*@await Component.InvokeAsync("TopKDR")*@
            </div>
        </div>
    </div>
</div>

nqostatsweb/src/nqostatsweb/Views/Players/Details.cshtml
@model IEnumerable<nqostatsweb.Models.MatchPlayerStats>

@{
    ViewData["Title"] = "Details";
}

<h2>Skill Stats for Matches</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TeamColor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KillEfficiency)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WeaponEfficiency)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TeamColor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KillEfficiency)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WeaponEfficiency)
                </td>
                <td>
                    <a asp-action="Index">Back to List</a>
                </td>
            </tr>
        }
    </tbody>
</table>

nqostatsweb/src/nqostatsweb/Views/Players/Highlights.cshtml
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet" />
<br/>
<br />
<br />
<br />
<div class="row-fluid">
    <div class="span4"><div class="well"><h4>Recent Matches</h4>
        </div>
    </div>
    <div class="span8">
        <div class="row-fluid">
            <div class="span6">
                <div class="well"><h4>Win Streak</h4>
                    <div>
                        <cache expires-after="@TimeSpan.FromMinutes(10)">
                            @await Component.InvokeAsync("TopWinStreak")                            
                            *last updated  @DateTime.Now.ToString()
                        </cache>
                        
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="well"><h4>Total Wins</h4>
                    <div>
                        @await Component.InvokeAsync("TopWins")
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <div class="well"><h4>Total Quads</h4>
                    <div>
                        @await Component.InvokeAsync("TopQuads")
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="well"><h4>Total Frags</h4>
                    <div>
                        @await Component.InvokeAsync("TopFrags")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span4">
        <div class="well"><h4>Highest Avg. Efficiency</h4>
            <div>
                @await Component.InvokeAsync("TopWeaponEfficiency")
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="well"><h4>Highest Win %</h4>
            <div>
                @await Component.InvokeAsync("TopWinPercent")
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="well"><h4>Highest KDR</h4>
            <div>
                @await Component.InvokeAsync("TopKDR")
            </div>
        </div>
    </div>
</div>

nqostatsweb/src/nqostatsweb/Views/Players/Index.cshtml
@model IEnumerable<nqostatsweb.Models.Players>

@{
    ViewData["Title"] = "Index";
}

<h2>Players</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            </td>
        </tr>
}
    </tbody>
</table>