nqostatsweb/src/nqostatsweb/Controllers/AllAveragesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using nqostatsweb.Data;
using nqostatsweb.Models.AllAveragesViewModels;
using Microsoft.EntityFrameworkCore;

namespace nqostatsweb.Controllers
{
    public class AllAveragesController : Controller
    {

        private readonly ApplicationDbContext _context;

        public AllAveragesController(ApplicationDbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            // call top 5 win percent
            var items = _context.Set<AllAveragesViewModel>().FromSql("call AverageStats('2017-03-21','2017-06-21')");
            await items.ToListAsync();
            var temp = items.Where(x => Convert.ToInt32(x.MatchesPlayed) >= 1);
            
            foreach (var player in temp )
            {
                if (player.Name.StartsWith("["))
                    player.Name = "\'" + player.Name + "\'";

                //player.AverageFrags = ConvertEfficiency(player.AverageFrags);
                //player.AverageDeaths = ConvertEfficiency(player.AverageDeaths);
                player.AverageEff = ConvertEfficiency(player.AverageEff);
                //player.AverageQuads = ConvertEfficiency(player.AverageQuads);
                //player.AvgFragsPerQuad = ConvertEfficiency(player.AvgFragsPerQuad);
                //player.AverageSelfKills = ConvertEfficiency(player.AverageSelfKills);
                //player.AverageTeamKills = ConvertEfficiency(player.AverageTeamKills);
                player.AverageSelfDmg = ConvertEfficiency(player.AverageSelfDmg);
                player.AverageTeamDmg = ConvertEfficiency(player.AverageTeamDmg);
                player.SGeff = ConvertEfficiency(player.SGeff);
                player.NailEff = ConvertEfficiency(player.NailEff);
                player.RLEff = ConvertEfficiency(player.RLEff);
                player.LGEff = ConvertEfficiency(player.LGEff);
                player.WinPercentage = ConvertEfficiency(player.WinPercentage);
                //player.KDR = ConvertEfficiency(player.KDR);
            }


            //items = items.Take(5);
            //return View(items);
            return View(temp);
        }

        private string ConvertEfficiency(string valueToconvert)
        {
            if (!String.IsNullOrEmpty(valueToconvert))
                return Math.Round(Convert.ToDecimal(valueToconvert) * 100, 2) + "%";
            return "N/A";
        }
    }
}

nqostatsweb/src/nqostatsweb/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using nqostatsweb.Data;
using nqostatsweb.Models;
using nqostatsweb.Models.MatchesViewModels;

namespace nqostatsweb.Controllers
{
    public class MatchesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MatchesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Matches
        public async Task<IActionResult> Index()
        {
            var startDate = new DateTime(2017, 03, 21);
            var endDate = new DateTime(2017, 06, 21);

            var matches = await _context.Match.Where(x => x.Date >= startDate && x.Date < endDate).ToListAsync();
            //var matches = await _context.Match.ToListAsync();
            var  listOfMatchesToDisplay = new List<MatchViewModel>();
            foreach (var match in matches)
            {
                var matchToDisplay = new MatchViewModel();
                matchToDisplay.Id = match.Id;
                matchToDisplay.MapName = match.MapName;
                matchToDisplay.MatchType = match.MatchType;
                var blah = Convert.ToDateTime(match.Date).ToString("ddd M/d/yyyy 'at' H:mm:ss CST");
                matchToDisplay.Date = blah;
                listOfMatchesToDisplay.Add(matchToDisplay);
            }
            listOfMatchesToDisplay.Reverse();
            return View(listOfMatchesToDisplay);
        }

        // GET: Matches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Match.Include(m1 => m1.Teams).SingleOrDefaultAsync(m => m.Id == id);
            if (match == null)
            {
                return NotFound();
            }

            var listOfTeamsToDisplay = new List<MatchTeamsViewModel>();
            foreach (var team in match.Teams)
            {
                var teamToDisplay = new MatchTeamsViewModel();
                teamToDisplay.Id = team.Id;
                teamToDisplay.MatchId = team.MatchId;
                teamToDisplay.TeamColor = team.TeamColor;
                teamToDisplay.TeamVerdict = team.TeamVerdict;
                teamToDisplay.TeamTotalFrags = team.TeamTotalFrags;
                teamToDisplay.TeamTotalQuads = team.TeamTotalQuads;
                teamToDisplay.TeamTotalPents = team.TeamTotalPents;
                teamToDisplay.TeamTotalEyes = team.TeamTotalEyes;
                teamToDisplay.TeamTotalRL = team.TeamTotalRL;
                teamToDisplay.TeamTotalLG = team.TeamTotalLG;
                teamToDisplay.TeamTotalGL = team.TeamTotalGL;
                teamToDisplay.TeamTotalSNG = team.TeamTotalSNG;
                teamToDisplay.TeamTotalNG = team.TeamTotalNG;
                teamToDisplay.TeamTotalMH = team.TeamTotalMH;
                teamToDisplay.TeamTotalRA = team.TeamTotalRA;
                teamToDisplay.TeamTotalYA = team.TeamTotalYA;
                teamToDisplay.TeamTotalGA = team.TeamTotalGA;
                teamToDisplay.TeamPlusRLPack = team.TeamPlusRLPack;
                teamToDisplay.TeamMinusRLPack = team.TeamMinusRLPack;
                teamToDisplay.TeamControlPercentage = (float)team.TeamControlPercentage*100;
                listOfTeamsToDisplay.Add(teamToDisplay);                
    }
            return View(listOfTeamsToDisplay);
        }

        // GET: Matches/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Matches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,MapName,MatchId,MatchText,MatchType")] Matches match)
        {
            if (ModelState.IsValid)
            {
                _context.Add(match);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(match);
        }

        // GET: Matches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Match.SingleOrDefaultAsync(m => m.Id == id);
            if (match == null)
            {
                return NotFound();
            }
            return View(match);
        }

        // POST: Matches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,MapName,MatchId,MatchText,MatchType")] Matches match)
        {
            if (id != match.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(match);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatchExists(match.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(match);
        }

        // GET: Matches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Match.SingleOrDefaultAsync(m => m.Id == id);
            if (match == null)
            {
                return NotFound();
            }

            return View(match);
        }

        // POST: Matches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var match = await _context.Match.SingleOrDefaultAsync(m => m.Id == id);
            _context.Match.Remove(match);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool MatchExists(int id)
        {
            return _context.Match.Any(e => e.Id == id);
        }
    }
}

nqostatsweb/src/nqostatsweb/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using nqostatsweb.Data;
using nqostatsweb.Models;

namespace nqostatsweb.Controllers
{
    public class PlayersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlayersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            var temp = _context.MatchPlayerStats.ToListAsync();
            return View(await _context.Players.ToListAsync());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.SingleOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            //var temp = await _context.MatchPlayerStats.ToListAsync();
            var temp = await _context.MatchPlayerStats.Where(p => p.PlayerId == player.Id).ToListAsync();
            return View(temp);
        }

        // GET: Players/Create
        public async Task<IActionResult> Highlights()
        {
            List<MatchPlayerStats> listItems = new List<MatchPlayerStats>();

            return View(listItems.ToList());
        }

        public IActionResult Badstats()
        {
            return View();
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Players player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.SingleOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Players player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.SingleOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Players.SingleOrDefaultAsync(m => m.Id == id);
            _context.Players.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PlayerExists(int id)
        {
            return _context.Players.Any(e => e.Id == id);
        }
    }
}

nqostatsweb/src/nqostatsweb/Controllers/TotalStatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using nqostatsweb.Data;
using nqostatsweb.Models.AllAveragesViewModels;
using Microsoft.EntityFrameworkCore;
using nqostatsweb.Models.TotalStatsViewModels;

namespace nqostatsweb.Controllers
{
    public class TotalStatsController : Controller
    {

        private readonly ApplicationDbContext _context;

        public TotalStatsController(ApplicationDbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            // call top 5 win percent
            var items = _context.Set<TotalStatsViewModel>().FromSql("call TotalStats('2017-03-21','2017-06-21')");
            await items.ToListAsync();
            var temp = items.Where(x => Convert.ToInt32(x.Games) >= 1);
            
            foreach (var player in temp )
            {
                if (player.Name.StartsWith("["))
                    player.Name = "\'" + player.Name + "\'";
            }


            //items = items.Take(5);
            //return View(items);
            return View(temp);
        }
    }
}

nqostatsweb/src/nqostatsweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NQO Stats</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
    <environment names="Development, Production">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <link href="~/jqwidgets/styles/jqx.base.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.arctic.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.black.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.metro.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.light.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.fresh.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.energyblue.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.highcontrast.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.dark.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.bootstrap.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.shinyblack.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.office.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.metrodark.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.darkblue.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.classic.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.web.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-lightness.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-darkness.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-overcast.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-le-frog.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-redmond.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-redmond.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-smoothness.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-sunny.css" rel="stylesheet" />
        <link href="~/jqwidgets/styles/jqx.ui-start.css" rel="stylesheet" />

        <script src="~/jqwidgets/jqx-all.js"></script>
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a asp-area="" asp-controller="Players" asp-action="Index" class="navbar-brand">Player Stats</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Players" asp-action="Highlights">Highlights</a></li>
                    <li><a asp-area="" asp-controller="Players" asp-action="Badstats">Badstats</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Records</a></li>
                    <li><a asp-area="" asp-controller="AllAverages" asp-action="Index">Averages</a></li>
                    <li><a asp-area="" asp-controller="TotalStats" asp-action="Index">Totals</a></li>
                    <li><a asp-area="" asp-controller="Matches" asp-action="Index">Matches</a></li>
                    <li><a asp-area="" asp-controller="Players" asp-action="Index">Players</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>*@
                    <li><a asp-area="" asp-controller="Home" asp-action="CoachsWords">Coach's Words</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - nqostatsweb</p>
        </footer>
    </div>

    @*<environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>*@

    @RenderSection("scripts", required: false)
</body>
</html>